version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo-showtime
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: showtime
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
